/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const showConfirmDialog: (typeof import('vant/es'))['showConfirmDialog']
  const showDialog: typeof import('vant/es')['showDialog']
}
